server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xichu
    password: xichu123
    url: jdbc:mysql://localhost:3307/xichu?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl